  GetCalendar:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${StackName}-GetCalendar-${ApiVersion}'
      Timeout: 10
      Handler: src/calendar/controller/calendarController.createCalendar
      Runtime: python3.7
      Policies:
      - AmazonRDSFullAccess
      Environment:
        Variables:
          NODE_ENV: '${NodeEnv}'
          DB_URL: '{{resolve:ssm:${StackName}-db-url:1}}'
          DB_USERNAME: '{{resolve:ssm:${StackName}-db-username:1}}'
          DB_PASSWORD: '{{resolve:ssm:${StackName}-db-password:1}}'
